title: 'Product Listing'
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              validate:
                - required
              display: 'Title (intern)'
              instructions_position: above
              listable: hidden
              visibility: visible
              replicator_preview: true
              input_type: text
              antlers: false
              hide_display: false
          -
            handle: type
            field:
              input_type: text
              antlers: false
              type: text
              display: Type
              icon: text
              listable: hidden
              instructions_position: above
              visibility: hidden
              replicator_preview: true
              hide_display: false
          -
            handle: heading
            field:
              input_type: text
              antlers: false
              type: text
              display: Heading
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: text
            field:
              restrict: false
              buttons:
                - bold
                - italic
                - unorderedlist
                - orderedlist
                - quote
                - link
                - image
                - table
              automatic_line_breaks: true
              automatic_links: false
              escape_markup: false
              heading_anchors: false
              smartypants: false
              table_of_contents: false
              antlers: false
              type: markdown
              display: Text
              icon: markdown
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
  settings:
    display: Settings
    sections:
      -
        display: Settings
        fields:
          -
            import: style
          -
            import: order
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
